Repository ganga-devs/ganga, pull requests merged in 2018-07, with the labels that each got.

#1229 Use IPython 5
  ganga/GangaCore/Runtime/IPythonMagic.py
  ganga/GangaCore/Runtime/bootstrap.py
  ganga/GangaCore/__init__.py
  ganga/GangaCore/test/Dockerfile
  ganga/GangaDirac/test/Dockerfile
  setup.py
Labels: enhancement

#1302 Fix the setting of colours in new version of ipython. Also remove cod…
  ganga/GangaCore/Runtime/bootstrap.py
  ganga/GangaCore/__init__.py
Labels: Core, bug, cleanup

#1303 Set LD_LIBRARY_PATH in DEV install script
  ganga/GangaRelease/tools/ganga-cvmfs-install-dev.sh
Labels: Core, bug
