Repository ganga-devs/ganga, pull requests merged in 2020-08, with the labels that each got.

#1753 Fix setting application platforms for LHCb
  ganga/GangaLHCb/Lib/RTHandlers/RTHUtils.py
Labels: LHCb

#1757 Allow XML repository use in gangaDB feature branch
  ganga/GangaCore/Core/GangaRepository/GangaRepositoryXML.py
  ganga/GangaCore/Core/GangaRepository/Registry.py
  ganga/GangaCore/Core/GangaRepository/SubJobXMLList.py
  ganga/GangaCore/GPIDev/Lib/Registry/JobRegistry.py
  ganga/GangaCore/GPIDev/Lib/Registry/PrepRegistry.py
  ganga/GangaCore/GPIDev/Lib/Tasks/TaskRegistry.py
Labels: Persistency, ready to merge

#1759 fix core transform
  ganga/GangaCore/GPIDev/Lib/Tasks/CoreTransform.py
Labels: bug
