Repository ganga-devs/ganga, pull requests merged in 2023-08, with the labels that each got.

#2094 PEP8 fixes for PR #2093 (bug_fixes) by autopep8
  ganga/GangaCore/Utility/logging/__init__.py
  ganga/GangaDirac/Lib/Backends/DiracBase.py
Labels: autopep8, automated pr

#2183 PEP8 fixes for PR #2182 (condor_modernisation) by autopep8
  ganga/GangaCore/Lib/Condor/Condor.py
Labels: autopep8, automated pr

#2182 Update Condor submit
  ganga/GangaCore/Lib/Condor/Condor.py
Labels: Core, modernisation

#2151 PEP8 fixes for PR #2150 (update_elementtree) by autopep8
  ganga/GangaGaudi/Lib/XMLSummary/schema.py
  ganga/GangaGaudi/Lib/XMLSummary/summary.py
  ganga/GangaLHCb/Lib/XMLSummary/schema.py
Labels: autopep8, automated pr

#2177 PEP8 fixes for PR #2176 (feat2105-replace-execute) by autopep8
  ganga/GangaCore/Core/GangaThread/WorkerThreads/ThreadPoolQueueMonitor.py
  ganga/GangaCore/Core/GangaThread/WorkerThreads/WorkerThreadPool.py
  ganga/GangaCore/Utility/execute.py
  ganga/GangaDirac/Lib/Backends/DiracUtils.py
  ganga/GangaGaudi/Lib/Applications/CMTUtils.py
  ganga/GangaGaudi/Lib/Applications/GaudiBase.py
  ganga/GangaLHCb/Lib/Applications/AppsBase.py
Labels: autopep8, automated pr

#2189 PEP8 fixes for PR #2188 (mesmith75-patch-1) by autopep8
  ganga/GangaDirac/Lib/Files/DiracFile.py
Labels: autopep8, automated pr

#2186 fix removeLFNs
  ganga/GangaDirac/Lib/Backends/DiracUtils.py
Labels: bug, DIRAC

#2187 PEP8 fixes for PR #2186 (removeLFN_fix) by autopep8
  ganga/GangaDirac/Lib/Backends/DiracUtils.py
Labels: autopep8, automated pr

#2195 PEP8 fixes for PR #2194 (fix_dirac_proxy_create) by autopep8
  ganga/GangaDirac/Lib/Credentials/DiracProxy.py
Labels: autopep8, automated pr
