Repository ganga-devs/ganga, pull requests merged in 2024-06, with the labels that each got.

#2354 PEP8 fixes for PR #2353 (mesmith75-patch-1) by autopep8
  ganga/GangaDirac/Lib/Backends/DiracBase.py
Labels: autopep8, automated pr

#2344 Re-add runMonitoring
  ganga/GangaCore/Core/MonitoringComponent/MonitoringService.py
  ganga/GangaCore/Core/__init__.py
Labels: enhancement, aio monitoring service

#2360 PEP8 fixes for PR #2359 (apptainer_fix) by autopep8
  ganga/GangaLHCb/Lib/Applications/GaudiExec.py
Labels: autopep8, automated pr

#2367 PEP8 fixes for PR #2366 (kill_fix) by autopep8
  ganga/GangaCore/GPIDev/Lib/Job/Job.py
Labels: autopep8, automated pr

#2364 Add optional BKQuery `retry_limit`
  ganga/GangaLHCb/Lib/LHCbDataset/BKQuery.py
Labels: enhancement, LHCb

#2365 PEP8 fixes for PR #2364 (bkgquery_improv) by autopep8
  ganga/GangaLHCb/Lib/LHCbDataset/BKQuery.py
Labels: autopep8, automated pr

#2363 Remove `finaliseOnMaster`
  ganga/GangaDirac/Lib/Backends/DiracBase.py
Labels: cleanup, DIRAC

#2368 PEP8 fixes for PR #2366 (kill_fix) by autopep8
  ganga/GangaCore/GPIDev/Lib/Job/Job.py
Labels: autopep8, automated pr

#2366 Fix master kill
  ganga/GangaCore/GPIDev/Lib/Job/Job.py
Labels: bug, Core
