Repository ganga-devs/ganga, pull requests merged in 2024-05, with the labels that each got.

#2339 Update Condor.py
  ganga/GangaCore/Lib/Condor/Condor.py
Labels: bug

#2345 PEP8 fixes for PR #2341 (update-docs) by autopep8
  doc/fill_gpi.py
Labels: autopep8, automated pr

#2342 Add SMOG options in BKQuery
  ganga/GangaLHCb/Lib/LHCbDataset/BKQuery.py
  ganga/GangaLHCb/Lib/Server/DiracLHCbCommands.py
Labels: enhancement, LHCb
