Repository ganga-devs/ganga, pull requests merged in 2024-02, with the labels that each got.

#2284 Fix Dirac job kill
  ganga/GangaDirac/Lib/Server/DiracCommands.py
Labels: cleanup, DIRAC

#2285 PEP8 fixes for PR #2284 (fix_job_kill) by autopep8
  ganga/GangaDirac/Lib/Server/DiracCommands.py
Labels: autopep8, automated pr

#2283 Remove interactive option
  ganga/GangaCore/Runtime/bootstrap.py
Labels: cleanup
